# Generated by Django 6.0 on 2026-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(default='Por ler', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserLivro',
        ),
    ]
