# Generated by Django 6.0 on 2026-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_user_categoria_livro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
